### ISSUE TITLE
Introduce Schema as a level in directory structure

### ISSUE THREAD

**Issue by ruslantalpa** [oelmekki/pgrebase#2]
Maybe this is already supported but it would be nice if this tool could understand code living in different schemas (used for namespacing)

It will make a really nice dev tool for working with things like PostgREST.
Thank you for the tool.

**Comment by oelmekki** [comment]
Hi @ruslantalpa , thanks, and you're welcome :)

I didn't try that myself because I run postgresql in docker containers, one per app, so I'll usually just put my stuff at top level.

That being said, [the way regexp are implemented to retrieve, say, function name](https://github.com/oelmekki/pgrebase/blob/master/function.go#L71) is to look for a space delimited name.

This means that if your sql contains `CREATE FUNCTION my_namespace.my_func()`, the name used in drop statement will be `my_namespace.my_func`. For the creation step, your file will be loaded as is.

I think that is enough to support namespaces. But then again, I didn't try it, so I recommend you try it on non important database first.

**Comment by ruslantalpa** [comment]
I thought that might be possible but that's not what i meant.
As i said, the point was to namespace some functions/modules, the way you describe it, 2 functions from different modules would live under the same directory and i could not look at the directory structure and say, ok, here is code for module1 and here is code for module2. It would not even be possible if they were both named the same.

Ideally (for me) there would be a top directory (under `sql/`) named after the schema (say `api`) then everything would go under it. Also in all the files you would not have to specify `schema.functionname` but just say `functionname` and the function would be added to the appropriate schema.

like this

```
$ tree sql/
sql/
├── public
    ├── functions/
    │   └── assign_user_to_team.sql
    ├── triggers/
    │   └── user_updated_at.sql
    ├── types/
    │   └── follower.sql
    └── views/
          └── user_json.sql
```

**Comment by oelmekki** [comment]
Oh, I see.

Well first, the directories under the target directory are walked, so one thing you can already do is:

```
$ tree ./sql/
./sql/
├── functions
│   ├── other
│   │   └── assign_user_to_team.sql
│   └── public
│       └── assign_user_to_team.sql
├── triggers
│   ├── other
│   │   └── user_updated_at.sql
│   └── public
│       └── user_updated_at.sql
└── views
    ├── other
    │   └── user_json.sql
    └── public
        └── user_json.sql
```

This works out of the box, but may not be very easy to look at your code if you think in terms of sql modules.

An other option, provided you have a not insanely large amount of modules and that code from one module does not depend on code from an other, would be to launch several instances:

```
$ tree ./sql/
./sql/
├── other
│   ├── functions
│   ├── triggers
│   └── views
└── public
    ├── functions
    ├── triggers
    └── views

$ pgrebase ./sql/public/ &
$ pgrebase ./sql/other/
```

(obviously better in several different shells, to have output)

I'm currently considering a more solid dependency resolver, for the `require` statements, the goal being to do real filesystem resolution rather than just the current filename matching (the reason why there are those functions/, triggers/, types/ and views/ directories). When it will be implemented, this should allow to be more permissive regarding the FS organization.

**Comment by ruslantalpa** [comment]
Option 2 works (didn't think of that) but still you would have to add the schema name inside each file for it to work.
Anyway, when the resolver is ready, please keep this usecase in mind (top directory is schema), if more code is going to be moving to the db, namespacing will be a must.
Thank you

**Comment by ruslantalpa** [comment]
As last thought :)
Since functions/views are in different files, everyone using it would need this tool, but when distributing it, it would be nice not to have ppl install it if they are just trying the code.
One way to do that (when't you have the dependency resolver) is to have  parameter that when executed against a directory, would generate a psql compatible files with includes for each file in the right order, then you can just execute that file and have the entire codebase loaded in the db.

`pgrebase --flag sql/ > sql/import_everything.sql`

**Comment by oelmekki** [comment]
> if more code is going to be moving to the db, namespacing will be a must.

Indeed. If have mixed feeling about automatically prepending namespace because I like the idea that user can take for granted that what they wrote in their file is indeed what will be executed on the database.

That being said, this could totally be an optional feature. Something like:

```
OPTIONS:
  -n: namespace mode.
      In namespace mode, your top level directories are namespace,
      and will be prefixed to your units names.
```

Love the idea of export as well :)
