### ISSUE TITLE
Error: Didn't find any sql file in pg_rebase_test

### ISSUE THREAD

**Issue by timuckun** [oelmekki/pgrebase#6]
I just downloaded your app and am trying to give it a spin. I created a directory structure like the instructions indicated (BTW why can't the app do that for me?) and ran it like

DATABASE_URL=postgresql://tim@localhost:5432/test_dev pgrebase pg_rebase_test

and I get the error Error: Didn't find any sql file in pg_rebase_test

What SQL file is it looking for?

**Comment by oelmekki** [comment]
Hi @timuckun ,

Can you show what your directory looks like?

Given your command, it's expected to look something like that:

```
$ tree pg_rebase_test/
pg_rebase_test/
├── functions
│   └── my_function.sql
├── triggers
└── views
```

In this example, PgRebase files are in `pg_rebase_test/`, and there is one function file. There need to be at least one sql file of course, or else PgRebase has nothing to do (but it doesn't need to be a function file, it could be a view or trigger file as well).


> BTW why can't the app do that for me?

It could :) Note that PgRebase is a very young project (started mid-november), so it's certainly rough around the edge. For now, my priorities are to make big impact changes, like adding a test suite to be sure there's no regression on change, building a proper dependency engine that could autodetect dependencies between sql files, or builtin support for multi-schema so that organizing namespaced code is made easier. 

This is also a perfect example of "scratching our own itch" project, not the kind of open source project out of google or facebook that are launched full featured. Features will be added iteratively based on needs and demand, but it was launch with the single feature that makes it useful : autoloading pg functional code.

**Comment by timuckun** [comment]
I think I misunderstood your project. I was under the impression it would connect to the database and pull all of those functions down into files on my machine.

Sorry.

**Comment by oelmekki** [comment]
My bad, I guess it means it was not clear enough :)

That would be a cool feature to bootstrap a PgRebase project, though!

**Comment by oelmekki** [comment]
I changed project description from "Easy postgres codebase management" to "Easy postgres codebase injection", I guess it will be clearer from the very start.
